[build]
  base = ""
  publish = "dist/serviceangular/browser"
  command = "npm run build --prod"

[functions]
  directory = "netlify/functions"

# Configuración para redirecciones
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200