[build]
  base = "." # Directorio base
  publish = "dist/serviceangular/browser/browser" # Actualiza esta ruta
  command = "npm run build --prod" # Comando para construir la aplicación

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true